1. gradient descent normal
2. gradient descent l2(ratio = 1)
3. sklearn logistic(penalty == 'none')
4. sklearn logistic(penalty == 'l2')
5. NN

** sklearn에서 어떤 트릭을 써서 성능을 향상시키는지는 불확실함  
** logistic에서 loss는 binary_crossentropy

In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

d = load_breast_cancer()

data = pd.DataFrame(d.data, columns=d.feature_names)
target = pd.DataFrame(d.target)

train_X, test_X, train_y, test_y = train_test_split(data, target, test_size=0.3, random_state=2019, shuffle=True)

In [2]:
d = (train_X - np.mean(train_X))/np.std(train_X)
data = d.copy()
test_X = (test_X - np.mean(test_X)) / np.std(test_X)
t = test_X.copy()

In [3]:
d['const'] = np.ones_like(d['mean area'])
t['const'] = np.ones_like(test_X['mean area'])

In [4]:
d

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
14     -0.116417      0.790962        0.063844  -0.220533         1.254004   
514     0.256038     -0.052228        0.213188   0.128310        -0.271490   
537    -0.692029      1.226849       -0.639215  -0.705696         2.018572   
331    -0.328039      0.014465       -0.306659  -0.402010        -0.006440   
79     -0.361899     -0.307091       -0.360929  -0.423742         0.252057   
..           ...           ...             ...        ...              ...   
24      0.707499      0.497989        0.733036   0.700401         1.181188   
190     0.021843      0.912439        0.095264  -0.131347         0.846235   
159    -0.914938     -1.507565       -0.952592  -0.817461        -1.509362   
370     0.622850      0.952931        0.692232   0.519206         0.112250   
72      0.862688      1.245904        0.904415   0.770396         0.817109   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
14           2.389836        1.598685             0.796560       0.911954   
514         -0.313884       -0.148491            -0.130305      -0.882069   
537          0.992043       -0.524804            -0.081073       1.130910   
331          0.186568       -0.196496            -0.478193      -0.175761   
79          -0.134868       -0.604094            -0.637694      -0.327617   
..                ...             ...                  ...            ...   
24           0.812839        0.834913             1.084165       0.650620   
190          2.616200        1.412492             0.443146       2.024390   
159         -1.234239       -1.057544            -1.053703      -1.302323   
370          0.888294        1.197167             0.984445       1.286298   
72           1.516452        1.046439             0.776214       0.410475   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
14                 2.165735  ...       1.053857         0.049098   -0.319986   
514               -0.513503  ...       0.392530         0.197541    0.153593   
537                1.745730  ...       1.083993        -0.624240   -0.689282   
331                0.434162  ...      -0.630433        -0.235616   -0.431478   
79                -0.389169  ...      -0.149925        -0.453234   -0.452932   
..                      ...  ...            ...              ...         ...   
24                 0.115747  ...       0.978516         2.073864    2.348271   
190                1.953458  ...       1.919441        -0.022155   -0.206207   
159               -0.774300  ...      -1.258275        -0.863234   -0.720409   
370               -0.054075  ...       0.889781         0.657715    0.501787   
72                 0.353800  ...       1.356895         1.319772    1.409202   

     worst smoothness  worst compactness  worst concavity  \
14           1.435091           3.430777         2.183769   
514         -0.320347          -0.253977         0.116111   
537          1.942218           0.499485        -0.629909   
331         -0.138302           0.500795         0.406709   
79          -0.133967          -0.227769        -0.459506   
..                ...                ...              ...   
24           2.102591           0.713730         1.043692   
190          0.923630           4.480381         2.967318   
159         -0.645428          -1.087108        -1.243360   
370          0.412169           1.425914         2.256799   
72           1.149020           3.213911         1.992573   

     worst concave points  worst symmetry  worst fractal dimension  const  
14               1.612591        1.088157                 3.580816    1.0  
514             -0.029137       -0.981803                -0.809866    1.0  
537              0.254544       -0.161066                 0.990338    1.0  
331             -0.231637        1.088157                 0.510443    1.0  
79              -0.523165       -0.198873                -0.234469   

In [5]:
def logit(x, y, p=False, lr=0.001):
#     if not p:
#         p = np.random.normal(0, 1, len(x[0]))
    t = np.array(list(map(lambda x: 1/(1 + np.exp(x)), x@p))) - y.flatten()
    
    res = t.T @ x
    return p + np.dot(res, lr/len(x)), np.sum(res)/len(x)


In [6]:
np.random.seed(0)
p1 = np.random.normal(0, 0.1, len(d.values[0]))
# p = np.zeros_like(d.columns)
for _ in range(200):
    p1, j = logit(d.values, train_y.values, p1, lr=0.01)
    print(_, '######')
    print(j)
    print(p1)
    if j < 0:
        break

0 ######
4.0166112072619375
[ 0.17910099  0.04125169  0.10057147  0.22664634  0.18744018 -0.09603188
  0.09720218 -0.01265458 -0.00958505  0.04041297  0.0161855   0.14476999
  0.07779636  0.0139882   0.04340219  0.03407701  0.150243   -0.01927413
  0.03080631 -0.08544458 -0.25246363  0.06668196  0.08926843 -0.07156957
  0.22783593 -0.14357039  0.006787   -0.01606135  0.15449773  0.14772073
  0.01419922]
1 ######
3.906019579690276
[ 0.181736    0.04246043  0.1032075   0.22914419  0.18809802 -0.09438651
  0.09933847 -0.01023475 -0.00887211  0.03976625  0.0179221   0.14412126
  0.07944471  0.01576275  0.04243205  0.03475611  0.15104512 -0.01807239
  0.03031157 -0.08549437 -0.24969201  0.06797383  0.09202865 -0.06898428
  0.22867172 -0.14175261  0.00894346 -0.01346711  0.15569073  0.1484799
  0.01291172]
2 ######
3.8007131040450117
[ 0.18431286  0.04364308  0.10578456  0.23158551  0.18873078 -0.09278928
  0.10142044 -0.00787342 -0.00818183  0.03912009  0.01961634  0.14348111
  0.08105104  

97 ######
1.0191218294738849
[ 0.31597898  0.10623632  0.23656151  0.3560866   0.20910696 -0.02706938
  0.20043443  0.10798408  0.01899741 -0.01009757  0.10621401  0.1066604
  0.16075883  0.10429392 -0.01164832  0.04885761  0.17224202  0.02565413
  0.00177741 -0.10879382 -0.10739186  0.13759688  0.23244933  0.06248742
  0.26695844 -0.05889507  0.1121052   0.11420492  0.21829901  0.17659499
 -0.07719886]
98 ######
1.0113500476596196
[ 0.31681696  0.10666494  0.23738881  0.35688536  0.20917368 -0.02675254
  0.20103216  0.10870277  0.01912496 -0.01050161  0.10679882  0.10641776
  0.16128088  0.10486378 -0.01198227  0.04881527  0.17225684  0.02582074
  0.0015916  -0.1090634  -0.10648727  0.13807702  0.233334    0.0633242
  0.26719259 -0.05844082  0.11271428  0.11497784  0.21870863  0.17671344
 -0.07789   ]
99 ######
1.0036998254320102
[ 0.31764916  0.10709126  0.23821035  0.35767877  0.20923928 -0.02643917
  0.20162556  0.10941642  0.0192511  -0.01090387  0.10738041  0.10617688
  0.1617998

In [7]:
def logit_l2(x, y, p=False, lr=0.001):
#     if not p:
#         p = np.random.normal(0, 1, len(x[0]))
    t = np.array(list(map(lambda x: 1/(1 + np.exp(x)), x@p))) - y.flatten()
    
    res = (t.T @ x) / len(x)
    return p + np.dot(res+2*p, lr), np.sum(res)/len(x)


In [8]:
np.random.seed(0)
p2 = np.random.normal(0, 0.1, len(d.values[0]))
# p = np.zeros_like(d.columns)
for _ in range(100):
    p2, j = logit_l2(d.values, train_y.values, p2, lr=0.01)
    print(_, '######')
    print(j)
    print(p2)
#     if j < 0:
#         break


0 ######
0.010091987957944564
[ 0.18262909  0.042052    0.10252894  0.23112812  0.1911753  -0.09798643
  0.09910235 -0.0129573  -0.00979149  0.04123416  0.01647359  0.14767853
  0.07931844  0.01423155  0.04428992  0.03474435  0.15323116 -0.01968445
  0.03143244 -0.08715278 -0.25756961  0.06798919  0.0909973  -0.0730539
  0.23237544 -0.14647912  0.00687852 -0.01643572  0.15756329  0.15065944
  0.01450912]
1 ######
0.009706741252943879
[ 0.18890403  0.04409027  0.10720209  0.23823556  0.19563706 -0.09832048
  0.10320085 -0.01081607 -0.00928899  0.0414006   0.01852631  0.14997668
  0.08253969  0.01627828  0.04419745  0.03610491  0.15708381 -0.01889116
  0.03156058 -0.0889573  -0.25996348  0.07062761  0.09556268 -0.07194369
  0.23783944 -0.14760836  0.00915364 -0.01418942  0.16189405  0.15441658
  0.01351332]
2 ######
0.009335848034178418
[ 0.19523356  0.04613173  0.11189619  0.2454156   0.20014368 -0.09872878
  0.10730735 -0.00870985 -0.00881347  0.04155979  0.02056455  0.15232299
  0.085

In [9]:
from sklearn.linear_model import LogisticRegression

lr1 = LogisticRegression(random_state=0, penalty='none').fit(data, train_y)
lr2 = LogisticRegression(random_state=0, penalty='l2').fit(data, train_y)

c:\users\young\anaconda3\envs\study\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\young\anaconda3\envs\study\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
lr1.coef_

array([[  316.37848285,   151.4229622 ,   324.13975465,   161.2011775 ,
         -148.81101821,   973.76017558,  -374.89819977,  -778.30114519,
          295.22923949,   328.84677296, -1075.56331898,   422.07215305,
         -314.54211295,  -679.00324082,   216.53859079,   372.46845816,
         -129.76629066,  -511.23441741,  -215.85515865,   614.32642001,
         -397.06155094,  -924.69861549,  -129.08076399,  -465.97479177,
          107.69792743,   248.71600429,  -328.82960147,  -553.23061992,
         -217.20681907, -1238.75682548]])

In [11]:
lr2.coef_

array([[-0.33959323, -0.3324814 , -0.31619422, -0.38415508, -0.1942301 ,
         0.53580951, -0.75830361, -0.85337633,  0.16949981,  0.37449158,
        -1.29453811,  0.30300204, -0.71504839, -0.88244554,  0.06239748,
         0.73100815, -0.23750998, -0.25108461,  0.08392654,  0.72630831,
        -0.89063267, -1.08602693, -0.67686454, -0.8596919 , -0.56072218,
        -0.03779392, -0.87076278, -0.68637943, -0.61672213, -0.67378698]])

In [12]:
p1

array([ 0.3806995 ,  0.14185831,  0.30028672,  0.41829073,  0.21246444,
       -0.00650879,  0.24633828,  0.1634582 ,  0.02734039, -0.04417314,
        0.1543836 ,  0.08835124,  0.20307832,  0.15026968, -0.03604917,
        0.0407835 ,  0.16998129,  0.0353628 , -0.01290862, -0.13376976,
       -0.03628514,  0.17819279,  0.30165544,  0.12860754,  0.28629274,
       -0.02592905,  0.15885512,  0.17372152,  0.25114757,  0.1845646 ,
       -0.13435388])

In [13]:
p2

array([ 1.70935491,  0.46099192,  1.13408617,  2.02797568,  1.33198976,
       -0.54711696,  0.96265064,  0.22824447, -0.04440699,  0.0653238 ,
        0.36608372,  0.88135217,  0.79081542,  0.35848514,  0.07348353,
        0.24546912,  1.10496111, -0.05073933,  0.09424962, -0.7491464 ,
       -1.39960689,  0.65170923,  1.06778898, -0.12402227,  1.67233635,
       -0.83586094,  0.31323136,  0.23201773,  1.25965072,  1.08727545,
       -0.15362823])

In [14]:
print('nomal:', accuracy_score(test_y, np.array(list(map(lambda x: 1 if 1/(1+x) > 0 else 0, np.dot(t.values @ p1, -1))))))
print('l2:', accuracy_score(test_y, np.array(list(map(lambda x: 1 if 1/(1+x) > 0 else 0, np.dot(t.values @ p2, -1))))))
print('lr1:', accuracy_score(test_y, lr1.predict(test_X)) )
print('lr2:', accuracy_score(test_y, lr2.predict(test_X)) )

nomal: 0.9239766081871345
l2: 0.935672514619883
lr1: 0.935672514619883
lr2: 0.9824561403508771


In [15]:
from keras import layers, models, optimizers
import keras.backend as K
from keras.regularizers import L1L2

m = models.Sequential()
m.add(layers.Dense(1, activation='sigmoid', kernel_regularizer=L1L2(l1=0, l2=0.01)))

m.compile(optimizer='adam',
         loss = 'binary_crossentropy'
         )

Using TensorFlow backend.


In [16]:
m.fit(data.values, train_y.values,
     epochs=150)

Epoch 1/150
398/398 [==============================] - 0s 854us/step - loss: 0.5039
Epoch 2/150
398/398 [==============================] - 0s 60us/step - loss: 0.4576
Epoch 3/150
398/398 [==============================] - 0s 60us/step - loss: 0.4195
Epoch 4/150
398/398 [==============================] - 0s 63us/step - loss: 0.3883
Epoch 5/150
398/398 [==============================] - 0s 60us/step - loss: 0.3619
Epoch 6/150
398/398 [==============================] - 0s 63us/step - loss: 0.3401
Epoch 7/150
398/398 [==============================] - 0s 58us/step - loss: 0.3216
Epoch 8/150
398/398 [==============================] - 0s 58us/step - loss: 0.3055
Epoch 9/150
398/398 [==============================] - 0s 65us/step - loss: 0.2915
Epoch 10/150
398/398 [==============================] - 0s 63us/step - loss: 0.2794
Epoch 11/150
398/398 [==============================] - 0s 60us/step - loss: 0.2687
Epoch 12/150
398/398 [==============================] - 0s 60us/step - loss: 0.2591


398/398 [==============================] - 0s 58us/step - loss: 0.1347
Epoch 99/150
398/398 [==============================] - 0s 55us/step - loss: 0.1346
Epoch 100/150
398/398 [==============================] - 0s 55us/step - loss: 0.1344
Epoch 101/150
398/398 [==============================] - 0s 80us/step - loss: 0.1342
Epoch 102/150
398/398 [==============================] - 0s 80us/step - loss: 0.1340
Epoch 103/150
398/398 [==============================] - 0s 68us/step - loss: 0.1338
Epoch 104/150
398/398 [==============================] - 0s 63us/step - loss: 0.1336
Epoch 105/150
398/398 [==============================] - 0s 58us/step - loss: 0.1334
Epoch 106/150
398/398 [==============================] - 0s 60us/step - loss: 0.1333
Epoch 107/150
398/398 [==============================] - 0s 58us/step - loss: 0.1331
Epoch 108/150
398/398 [==============================] - 0s 55us/step - loss: 0.1330
Epoch 109/150
398/398 [==============================] - 0s 55us/step - loss: 0.

In [17]:
accuracy_score(test_y, m.predict_classes(test_X))

0.9824561403508771