정의한 오차는 줄어드는데 y에는 가까이 가지 않는 현상 관찰  
어디서 문제가 생긴것인가..

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler

d = load_boston()

std = StandardScaler()
data = pd.DataFrame(std.fit_transform(d.data), columns=d.feature_names)
target = std.fit_transform(d.target.reshape(-1,1))

In [2]:
data

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1   -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2   -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3   -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4   -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.413229 -0.487722  0.115738 -0.272599  0.158124  0.439316  0.018673   
502 -0.415249 -0.487722  0.115738 -0.272599  0.158124 -0.234548  0.288933   
503 -0.413447 -0.487722  0.115738 -0.272599  0.158124  0.984960  0.797449   
504 -0.407764 -0.487722  0.115738 -0.272599  0.158124  0.725672  0.736996   
505 -0.415000 -0.487722  0.115738 -0.272599  0.158124 -0.362767  0.434732   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501  
..        ...       ...       ...       ...       ...       ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.418147  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.500850  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.983048  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.865302  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.669058  

[506 rows x 13 columns]

In [3]:
data['const'] = np.ones_like(data.iloc[:,0])

In [4]:
class Percep:
    def __init__(self, x, y, activation='linear'):
        np.random.seed(0)
        self.data = x
        self.target = y
        self.w = np.random.normal(0, 1, len(x.values[0]))
        self.activation = activation
        self.loss = np.Inf
        self.hist = []
        
    def update(self, x, y, w, lr=0.0001):
        y = y.flatten()
        a = x @ w
        if self.activation == 'sigmoid':
            y_hat = np.array(list(map(lambda x: 1 / (1 + np.exp(-x)), a))).flatten()
            h = y_hat * (1 - y_hat)
        elif self.activation == 'relu':
            y_hat = np.array(list(map(lambda x: max(0, x), a))).flatten()
            h = np.array(list(map(lambda x: 1 if x > 0 else 0, y_hat))).flatten()
        else:
            y_hat = a
            h = 1

        diff  = y - y_hat

        c = h * diff

        return w - np.dot(x.values.T @ c, -lr/len(x)), (y - y_hat).T @ (y - y_hat) / len(x)
        
    def fit(self):
        for _ in range(5000):
            w, c = self.update(self.data, self.target, self.w)
            self.hist.append(c)
            if np.abs(c-self.loss) < 1e-4:
                break
            else:
                self.w = w
                self.loss = c
                       

In [5]:
nn = Percep(data, target, activation = 'linear')

In [6]:
nn.fit()

In [7]:
nn.hist

[39.776266390848825,
 39.738687864682866,
 39.70115359075982,
 39.66366351520088,
 39.62621758419306,
 39.58881574398937,
 39.55145794090849,
 39.514144121334816,
 39.47687423171839,
 39.43964821857477,
 39.40246602848493,
 39.365327608095214,
 39.32823290411734,
 39.29118186332817,
 39.25417443256968,
 39.21721055874894,
 39.18029018883798,
 39.143413269873726,
 39.10657974895789,
 39.06978957325694,
 39.033042690002,
 38.996339046488764,
 38.95967859007743,
 38.923061268192576,
 38.88648702832317,
 38.849955818022394,
 38.81346758490765,
 38.77702227666043,
 38.7406198410262,
 38.704260225814465,
 38.66794337889847,
 38.63166924821541,
 38.59543778176603,
 38.559248927614824,
 38.523102633889756,
 38.48699884878235,
 38.45093752054743,
 38.41491859750324,
 38.37894202803119,
 38.3430077605759,
 38.30711574364508,
 38.27126592580942,
 38.235458255702554,
 38.199692682021016,
 38.16396915352403,
 38.12828761903363,
 38.09264802743439,
 38.057050327673466,
 38.02149446876052,
 37.985980

In [8]:
data.values @ nn.w

array([ 5.99875874e-01, -2.91727890e-01, -6.61071138e-01, -7.25698902e-01,
       -7.16268880e-01, -4.84305685e-01,  5.69364688e-01,  7.28592304e-01,
        6.89081541e-01,  7.42239724e-01,  6.62354312e-01,  8.31231479e-01,
        2.93718495e-01,  2.44942819e-02, -1.97642942e-01, -3.69150461e-02,
       -2.97505388e-01, -1.66791073e-01, -1.73331567e+00, -1.58525010e-01,
       -1.86850596e-01, -6.07111957e-02, -6.76316239e-02,  4.62049178e-02,
        5.00905163e-02, -1.17292388e+00, -1.15322352e-01, -1.26024738e+00,
       -1.74927583e-01, -4.00740284e-01, -4.37622366e-01, -1.46903121e-01,
       -2.50903525e+00, -4.86177535e-01, -2.16444607e+00, -6.37257002e-01,
       -9.41066313e-01, -6.44794041e-01, -8.32475005e-01,  1.26400965e+00,
        1.10896713e+00, -1.08396101e+00, -8.94050021e-01, -7.69503157e-01,
       -6.07465916e-01, -5.44278509e-01, -6.32215642e-01, -3.64415333e-01,
       -1.38909302e-01, -1.92511395e-01,  2.74338929e-01,  3.58595041e-01,
        4.76095057e-02,  

In [9]:
nn.target

array([[ 0.15968566],
       [-0.10152429],
       [ 1.32424667],
       [ 1.18275795],
       [ 1.48750288],
       [ 0.6712218 ],
       [ 0.03996443],
       [ 0.49708184],
       [-0.65659542],
       [-0.39538548],
       [-0.81985164],
       [-0.39538548],
       [-0.09064054],
       [-0.23212926],
       [-0.47157171],
       [-0.286548  ],
       [ 0.06173193],
       [-0.54775795],
       [-0.25389676],
       [-0.47157171],
       [-0.97222411],
       [-0.31919924],
       [-0.79808414],
       [-0.87427038],
       [-0.75454915],
       [-0.93957286],
       [-0.64571167],
       [-0.84161913],
       [-0.44980422],
       [-0.16682677],
       [-1.07017784],
       [-0.87427038],
       [-1.0157591 ],
       [-1.02664285],
       [-0.98310786],
       [-0.39538548],
       [-0.27566425],
       [-0.16682677],
       [ 0.23587189],
       [ 0.89978051],
       [ 1.34601416],
       [ 0.4426631 ],
       [ 0.30117438],
       [ 0.23587189],
       [-0.14505928],
       [-0

In [10]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(data, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
lr.coef_

array([[-0.10101708,  0.1177152 ,  0.0153352 ,  0.07419883, -0.22384803,
         0.29105647,  0.00211864, -0.33783635,  0.28974905, -0.22603168,
        -0.22427123,  0.09243223, -0.40744693,  0.        ]])

In [12]:
# breast cancer
from sklearn.datasets import load_breast_cancer
import pandas as pd 
from sklearn.model_selection import train_test_split

d = load_breast_cancer()

data = pd.DataFrame(d.data, columns=d.feature_names)
target = pd.DataFrame(d.target)

train_X, test_X, train_y, test_y = train_test_split(data, target, test_size=0.3, random_state=2019, shuffle=True)

In [13]:
data = (data - np.mean(data)) / np.std(data)

In [14]:
nn = Percep(data, target.values.flatten(), activation = 'sigmoid')

In [15]:
nn.fit()

In [16]:
nn.w

array([ 1.76405038,  0.40015642,  0.97873605,  2.24089135,  1.86755849,
       -0.97727862,  0.95008713, -0.15135871, -0.10321889,  0.41059945,
        0.14404248,  1.45427422,  0.76103667,  0.12167388,  0.44386396,
        0.33367397,  1.49407864, -0.20515899,  0.31306821, -0.85409554,
       -2.55299186,  0.65361786,  0.86443419, -0.74216691,  2.26975462,
       -1.45436677,  0.04575718, -0.18718556,  1.53277869,  1.46935859])

In [17]:
a = list(map(lambda x: 1 if x > 0 else 0, data @ nn.w))

In [18]:
from sklearn.metrics import accuracy_score

accuracy_score(target, a)

0.17223198594024605

In [19]:
nn.hist

[0.753765540338261, 0.7537647092443076]