In [1]:
import numpy as np

In [2]:
obj = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]
obj = np.array(obj)

In [3]:
obj

array([[0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0]])

In [4]:
def pi(a):
    for i in range(len(a)):
        if a[i] == np.nan:
            a[i] = 0
            
    s = np.nansum(a)
    if s == 0:
        s = 1e-5
        print('here')
    for i in range(len(a)):
        a[i] /= s
    return a

def get_pi(a):
    for i in range(len(a)):
        for j in range(len(a[0])):
            a[i][j] = pi(a[i][j])
    return a

In [5]:
def action(s):
    # eps는 사전 설정
    ## s_next 생성
    if np.random.rand() > eps:
        return np.argmax(v[s])
    else:
        return np.random.choice([0, 1, 2, 3]) # 상하좌우
    
def state_map(s, a):
    s = list(s)
    if a == 0:
        s[0] -= 1
    elif a == 1:
        s[0] += 1
    elif a == 2:
        s[1] -= 1
    else:
        s[1] += 1
    return tuple(s)


In [6]:
def update(s, a, r, s_next, v):
    # lr, gamma 는 위에서 설정하기
    if s_next == goal:
        v[s][a] = v[s][a] + lr * (r - v[s][a])
    else:
        v[s][a] = v[s][a] + lr * (r + gamma*np.max(v[s_next]) - v[s][a])
        
#     v[s] = pi(v[s])
    return v


In [7]:
def is_wall(s):
    if s[0] < 0 or s[0] > 3:
        return True
    elif s[1] < 0 or s[1] > 4:
        return True
    elif obj[s] == 1:
        return True
    else:
        return False

In [8]:
def play(s):
    global v, fail_hist, hist, eps
    
    while 1:
        eps *= 0.99
        hist.append(s)
#         print(s)
        a = action(s)
        s_next = state_map(s, a)
#         print(a, s, s_next)
        
#         if (0 > s[0] or s[0] > 3) or (0 > s[1] or s[1] > 4) or obj[s] == 1: ## 가면 안되는 곳
        if is_wall(s_next):
            fail_hist.append((s, s_next))
#             r = -1
            v[s][a] = 0
            v[s] = pi(v[s])
#             v = update(s, a, r, s_next, v)
#             print(v[s], s_next)
            s_next = (0, 0)
            
            
        elif s_next[0] == goal[0] and s_next[1] == goal[1]: ## 도착
            r = 1
            v = update(s, a, r, s_next, v)
            break
        else: ## 갈곳이 남음
            r = 0
            v = update(s, a, r , s_next, v)
            
        print(v[s])
        fake_obj[s_next] = 2
        print(fake_obj)
        fake_obj[s_next] = obj[s_next]
        print(eps)
            
        s = s_next

In [9]:
shape = obj.shape
value = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]
for i in range(shape[0]):
    for j in range(shape[1]):
        value[i][j] = [0.25, 0.25, 0.25, 0.25] # 위, 아래, 좌, 우
v = np.array(value)

In [10]:
lr = 0.1
eps = 0.5
gamma = 0.9
v = np.array(value)
fail_hist = []
hist = []
fake_obj = obj.copy()

s_0 = (0, 0)
goal = (3, 4)

for i in range(100):
    play(s_0)
    print('succes', i)
    print(eps)
    eps = 0.5

[0.         0.33333333 0.33333333 0.33333333]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.495
[0.         0.33333333 0.33333333 0.33333333]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.49005
[0.         0.3225     0.33333333 0.33333333]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.48514949999999996
[0.255 0.25  0.25  0.25 ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.480298005
[0.         0.32603201 0.33698399 0.33698399]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47549502494999996
[0.         0.49174079 0.         0.50825921]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47074007470049994
[0.         0.49174079 0.         0.47993329]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.46603267395349496
[0.25       0.25       0.26925667 0.25      ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.46137234721396
[0.         0.46551671 0.         0.47993329]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4567

0.004057216813377119
[0.3181505  0.31844821 0.         0.31889385]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
0.004016644645243348
[0.49748744 0.         0.         0.50251256]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.003976478198790915
[0.         0.30857961 0.         0.30792958]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.003936713416803005
[0.30943196 0.         0.30753104 0.29991169]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.0038973462826349748
[0.         0.30598788 0.         0.30792958]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.003858372819808625
[0.31037606 0.31232753 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.0038197890916105387
[0.         0.30598788 0.         0.3049855 ]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.0037815912006944332
[0.         0.         0.50627166 0.49372834]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.003743775288687489
[0.         0.30

2.6657874271693756e-05
[0.         0.         0.30898476 0.30904286]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.6391295528976818e-05
[0.         0.         0.31110625 0.31005781]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.612738257368705e-05
[0.         0.30892506 0.31194152 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.586610874795018e-05
[0.30373797 0.25       0.25       0.25      ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.5607447660470678e-05
[0.         0.30892506 0.30874693 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.5351373183865972e-05
[0.         0.         0.30780948 0.31005781]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.509785945202731e-05
[0.         0.         0.30898476 0.30604378]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.4846880857507038e-05
[0.         0.         0.30780948 0.30685528]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
2.4598412048931966e-05
[0. 

[0.3350404  0.         0.33502807 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
2.781018402157497e-07
[0.         0.32526433 0.25389262 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
2.753208218135922e-07
[0.33081015 0.         0.33502807 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
2.725676135954563e-07
[0.         0.32289043 0.25389262 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
2.6984193745950174e-07
[0.33081015 0.         0.33049887 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [2 0 1 1 0]]
2.6714351808490674e-07
[0.26233711 0.         0.         0.319509  ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
2.6447208290405766e-07
[0.32678927 0.         0.33049887 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 2 1 0 0]
 [0 0 1 1 0]]
2.6182736207501707e-07
[0.         0.32034628 0.25389262 0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 2 1 1 0]]
2.592090884542669e-07
[0.32678927 0.         0.326

[0.31529134 0.32556011 0.         0.31629065]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
1.772991874209957e-09
[0.33001475 0.         0.         0.33360955]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
1.7552619554678574e-09
[0.31529134 0.32302896 0.         0.31629065]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
1.7377093359131789e-09
[0.33001475 0.         0.         0.32664776]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
1.7203322425540472e-09
[0.2926646 0.25      0.25      0.25     ]
[[0 0 0 0 1]
 [0 1 1 0 2]
 [0 0 1 0 0]
 [0 0 1 1 0]]
1.7031289201285067e-09
[0.         0.30965701 0.31580228 0.        ]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
1.6860976309272217e-09
[0.31529134 0.32042739 0.         0.31629065]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
1.6692366546179495e-09
[0.32585174 0.         0.         0.32664776]
[[0 0 0 0 1]
 [0 1 1 2 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
1.6525442880717699e-09
[0.31529134 0.31778295 0.    

[0.         0.         0.44990467 0.5115318 ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.17580460327901115
[0.         0.48041222 0.49606534 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.17404655724622103
[0.         0.         0.44990467 0.5050245 ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.17230609167375882
[0.         0.48041222 0.49191101 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.17058303075702122
[0.         0.         0.44990467 0.49879404]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.168877200449451
[0.         0.48041222 0.48761137 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.1671884284449565
[0.         0.         0.44990467 0.49279966]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.16551654416050693
[0.         0.48041222 0.4832022  0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.16386137871890186
[0.         0.         0.44990467 0.48700789]
[[0 0

 [0 0 1 1 0]]
0.33786452453014154
[0.         0.         0.46141119 0.46157209]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.33448587928484014
[0.         0.         0.49046664 0.49539764]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.33114102049199173
[0.         0.         0.46141119 0.46000067]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3278296102870718
[0.         0.         0.49046664 0.49119653]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3245513141842011
[0.         0.49623722 0.50376278 0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.32130580104235906
[0.         0.48924735 0.         0.48863052]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.31809274303193547
[0.47375096 0.46721233 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.31491181560161613
[0.42488749 0.3029685  0.         0.28035099]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3117626974456
[0.47040812 0.467212

[0.         0.         0.49915033 0.49516578]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3735860471657981
[0.         0.49868361 0.50131639 0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3698501866941401
[0.         0.48282105 0.         0.48622019]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3661516848271987
[0.45621993 0.45656149 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3624901679789267
[0.         0.49824613 0.         0.50175387]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3588652662991374
[0.         0.49824613 0.         0.49381512]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.35527661363614604
[0.         0.         0.46720856 0.46858286]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3517238474997846
[0.         0.50223323 0.         0.49776677]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.34820660902478673
[0.         0.49310044 0.         0.49776677]
[[0 0 0 

[0.5016942  0.48594545 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.25499287312478264
[0.41985474 0.34522032 0.         0.24834069]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2524429443935348
[0.49546767 0.48594545 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24991851494959946
[0.         0.48594376 0.         0.48356173]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24741932980010348
[0.         0.         0.48862201 0.48643873]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24494513650210245
[0.         0.         0.49508892 0.4987634 ]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24249568513708142
[0.         0.         0.48349475 0.48643873]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2400707282857106
[0.         0.48194147 0.         0.48356173]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2376700210028535
[0.48944146 0.48594545 0.         0.        ]
[[2 0

0.4089534687986153
[0.49211373 0.48436025 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.40486393411062915
[0.         0.48233394 0.         0.48301828]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4008152947695229
[0.         0.         0.47473557 0.47363927]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.39680714182182764
[0.         0.48233394 0.         0.47744265]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3928390704036094
[0.         0.         0.50057799 0.49942201]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.38891067969957327
[0.         0.48233394 0.         0.47475041]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.38502157290257755
[0.         0.         0.49393024 0.49942201]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3811713571735518
[0.         0.47839078 0.         0.47475041]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.37735964360181623
[0.48595752 0.48436025 0.       

 [0 0 1 1 0]]
0.37735964360181623
[0.         0.         0.49594093 0.49878499]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3735860471657981
[0.         0.         0.49289418 0.4966352 ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3698501866941401
[0.         0.48849847 0.         0.49096796]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3661516848271987
[0.48716833 0.48711594 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3624901679789267
[0.         0.48849847 0.         0.48656833]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3588652662991374
[0.         0.         0.49289418 0.49186233]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.35527661363614604
[0.         0.         0.49594093 0.493708  ]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3517238474997846
[0.         0.50182111 0.49817889 0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.34820660902478673
[0.         0.483493

 [0 0 1 1 0]]
0.20856043996661022
[0.         0.         0.4910955  0.49271866]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.20647483556694413
[0.         0.49166608 0.         0.49334909]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.20441008721127468
[0.50465317 0.49534683 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.20236598633916195
[0.         0.49166608 0.         0.48835886]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.20034232647577033
[0.         0.         0.4910955  0.48788994]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.19833890321101263
[0.         0.         0.48863005 0.49189897]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.1963555141789025
[0.         0.         0.4862359  0.48788994]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.19439195903711348
[0.         0.50168732 0.         0.49831268]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.19244803944674235
[0.         0.4

[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2681341126035925
[0.         0.         0.48083353 0.48945799]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2654527714775566
[0.         0.         0.48692503 0.48350639]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.262798243762781
[0.         0.49692335 0.         0.49129266]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2601702613251532
[0.         0.         0.48295562 0.48350639]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25756855871190165
[0.         0.48807489 0.         0.49129266]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25499287312478264
[0.45367768 0.44483828 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.2524429443935348
[0.40482592 0.34289456 0.         0.25502814]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24991851494959946
[0.45367768 0.43678878 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0

0.22376160688190533
[0.24917495 0.51940563 0.         0.24155687]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 2 0]
 [0 0 1 1 0]]
0.22152399081308627
[0.35662491 0.         0.         0.68805769]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 2]
 [0 0 1 1 0]]
0.2193087509049554
succes 53
0.21711566339590585
[0.         0.50095238 0.         0.49904762]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.495
[0.         0.49288601 0.         0.49904762]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.49005
[0.46435014 0.45948161 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.48514949999999996
[0.43372066 0.35042724 0.         0.32735374]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.480298005
[0.46282941 0.45948161 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47549502494999996
[0.         0.49288601 0.         0.49326609]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47074007470049994
[0.         0.         0.50168582

 [0 0 1 1 0]]
0.480298005
[0.         0.         0.49976998 0.49188022]
[[0 0 0 2 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47549502494999996
[0.         0.50707628 0.48782951 0.        ]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.47074007470049994
[0.         0.         0.49401026 0.49188022]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.46603267395349496
[0.         0.         0.48606854 0.48855669]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.46137234721396
[0.         0.48215337 0.         0.48292799]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.45675862374182036
[0.         0.         0.48606854 0.48416194]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.45219103750440215
[0.         0.         0.50108026 0.49891974]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.44766912712935814
[0.         0.48215337 0.         0.47838136]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.44319243585806456
[0.         0.         0.

 [0 0 1 1 0]]
0.44319243585806456
[0.         0.50196927 0.         0.49803073]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4387605114994839
[0.         0.50196927 0.         0.49803073]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.43437290638448905
[0.         0.50196927 0.         0.492992  ]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.43002917732064416
[0.         0.         0.49282066 0.49730968]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4257288855474377
[0.         0.49670223 0.         0.492992  ]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4214715966919633
[0.49066146 0.49922098 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.4172568807250437
[0.        0.4919619 0.        0.492992 ]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.41308431191779327
[0.49066146 0.48592171 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.4089534687986153
[0.40692031 0.30337606 

[0.49390989 0.48198535 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3928390704036094
[0.        0.4995245 0.        0.5004755]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.38891067969957327
[0.         0.4995245  0.         0.49480112]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.38502157290257755
[0.         0.         0.48868897 0.49061526]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3811713571735518
[0.         0.50237517 0.         0.49762483]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.37735964360181623
[0.         0.49658954 0.         0.49762483]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3735860471657981
[0.48930513 0.48198535 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3698501866941401
[0.         0.49658954 0.         0.49201772]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.3661516848271987
[0.         0.         0.48868897 0.48548273]
[[0 0 2 0 1

0.2708425379834268
[0.         0.48724058 0.         0.48554461]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2681341126035925
[0.         0.         0.49347866 0.50041443]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2654527714775566
[0.         0.48169859 0.         0.48554461]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.262798243762781
[0.47916686 0.47089145 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.2601702613251532
[0.43383231 0.35192988 0.         0.31953411]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25756855871190165
[0.47494918 0.47089145 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25499287312478264
[0.         0.49801187 0.         0.50198813]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2524429443935348
[0.         0.49095611 0.         0.50198813]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.24991851494959946
[0.4726332  0.47089145 0.         0

[0.49872278 0.48555846 0.         0.        ]
[[0 0 0 0 1]
 [0 1 1 0 0]
 [2 0 1 0 0]
 [0 0 1 1 0]]
0.2735783211953806
[0.38897468 0.34791316 0.         0.28384629]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2708425379834268
[0.49157469 0.48555846 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2681341126035925
[0.         0.4714836  0.         0.47347261]
[[0 0 0 0 1]
 [2 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2654527714775566
[0.48502975 0.48555846 0.         0.        ]
[[2 0 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.262798243762781
[0.         0.4714836  0.         0.47103888]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.2601702613251532
[0.         0.         0.4938245  0.49390804]
[[0 0 2 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25756855871190165
[0.         0.         0.49217888 0.49731326]
[[0 2 0 0 1]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 1 1 0]]
0.25499287312478264
[0.         0.         0.4938245  0.48927543]
[[0 0 2 0

In [11]:
v

array([[[0.        , 0.49330304, 0.        , 0.48179566],
        [0.        , 0.        , 0.47578912, 0.47302446],
        [0.        , 0.        , 0.48827213, 0.49071194],
        [0.        , 0.52914276, 0.46855134, 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ]],

       [[0.48267053, 0.4776729 , 0.        , 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.20309126, 0.54036033, 0.        , 0.26438776],
        [0.        , 0.56554842, 0.49951063, 0.        ]],

       [[0.41626747, 0.34791316, 0.        , 0.28384629],
        [0.        , 0.50060231, 0.49939769, 0.        ],
        [0.25      , 0.25      , 0.25      , 0.25      ],
        [0.32112353, 0.        , 0.        , 0.68286965],
        [0.18804869, 0.80024537, 0.16605254, 0.        ]],

       [[0.47465709, 0.        , 0.        , 0.52534291],
        [0.42719854, 0.        , 0.53148361, 0.        ],
        

In [12]:
value = [
    [0, 0, 0, 0, 1], 
    [0, 1, 1, 0, 0], 
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
]

In [13]:
hist

[(0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (2, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 2),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (2, 0),
 (3, 0),
 (2, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (0, 0),
 (1, 0),
 (0, 0),
 (0, 0),
 (0, 1),
 (0, 0),
 (1, 0),
 (2, 0),
 